// <auto-generated />
namespace anthR.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class MasterSite_LiveBidMasterSiteId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MasterSite_LiveBidMasterSiteId));
        
        string IMigrationMetadata.Id
        {
            get { return "201503021556316_MasterSite_LiveBidMasterSiteId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
