// <auto-generated />
namespace anthR.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class staffontask_cascadedelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(staffontask_cascadedelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201501091415017_staffontask_cascadedelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
